name: Scheduled Task

on:
  workflow_dispatch:  
  schedule:
    - cron: '*/5 * * * *'  # Exécution automatique toutes les 5 minutes
permissions:
  contents: write

jobs:
  your-job:
    name: Exécution de l'extracteur météo
    strategy:
      matrix:
        os: [ubuntu-latest]  
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      - name: Exécuter l'extracteur météo et enregistrer
        run: |
            chmod +x Extracteur_Météo.sh
            ./Extracteur_Météo.sh
            git add .
            git commit -m "mise à jour"
            git push

          
              
