name: Scheduled Task

on:
  workflow_dispatch:  
  schedule:
    - cron: '*/5 * * * *'  # Exécution automatique toutes les 5 minutes

jobs:
  your-job:
    name: Exécution de l'extracteur météo
    strategy:
      matrix:
        os: [ubuntu-latest]  
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Exécuter l'extracteur météo
        run: |
            chmod +x Extracteur_Météo.sh
            ./Extracteur_Météo.sh
          
              
